import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {


    'en': {
      // Status
      'status_healthy': 'Healthy',
      'status_diseased': 'Diseased',
      'status_unknown': 'Unknown',

// Crops
      'crop_maize': 'Maize',
      'crop_cassava': 'Cassava',
      'crop_unknown': 'Unknown',

// Diagnoses
      'diagnosis_mosaic': 'Mosaic Disease',
      'diagnosis_leaf_blight': 'Leaf Blight',
      'diagnosis_gray_leaf_spot': 'Gray Leaf Spot',
      'diagnosis_brown_streak': 'Brown Streak Disease',
      'diagnosis_healthy': 'Healthy',
      'diagnosis_unknown': 'Unknown',

      'analyzing_leaf': 'Analyzing leaf...',

      'app_title': 'Smart Leaf Doctor',
      'scan_now': 'Scan Leaf',
      'select_image': 'Select Image',
      'capture_image': 'Capture Image',
      'analysis_result': 'Analysis Result',
      'crop_type': 'Crop Type',
      'diagnosis': 'Diagnosis',
      'confidence': 'Confidence',
      'symptoms': 'Symptoms',
      'treatment': 'Treatment',
      'healthy_leaf': 'Leaf is Healthy ✅',
      'unknown_crop': 'Unknown Crop',
      'unknown_disease': 'Unknown Disease',
      'try_again': 'Try Again',
      'result': 'Result',
      'advice': 'Advice',
      'success': 'Success',
      'clear_photo': 'Please upload a clear leaf photo.',
      'language': 'Language',
      'ok': 'OK',
      'retake_photo': 'Retake Photo',
      'Scan & diagnose crop diseases instantly': 'Scan & diagnose crop diseases instantly',
      'Empowering agriculture through smart image diagnostics': 'Empowering agriculture through smart image diagnostics',
      'Oops! That’s not a cassava or maize leaf. Please upload or capture a leaf from one of those crops to get accurate results.': "Oops! That’s not a cassava or maize leaf. Please upload or capture a leaf from one of those crops to get accurate results.",
      'Unknown': 'Unknown',
      'Cassava brown streak detected. Use resistant cassava varieties, remove infected plants promptly, and practice crop rotation to reduce spread.': 'Cassava brown streak detected. Use resistant cassava varieties, remove infected plants promptly, and practice crop rotation to reduce spread.',
      'Maize gray leaf spot detected. Apply recommended fungicides, rotate crops, and plant resistant maize hybrids to protect yield.': 'Maize gray leaf spot detected. Apply recommended fungicides, rotate crops, and plant resistant maize hybrids to protect yield.',
      'none': 'none',
      'cassava': 'cassava',
      'maize': 'maize',
      'Cassava_Healthy': 'Cassava_Healthy',
      'Cassava_Mosaic_Disease': 'Cassava_Mosaic_Disease',
      'Maize_Healthy': 'Maize_Healthy',
      'Cassava_Brown_Streak_Disease':'Cassava_Brown_Streak_Disease',
      'Maize_Gray_Leaf_Spot':'Maize_Gray_Leaf_Spot',
      'Maize_Leaf_Blight': 'Maize_Leaf_Blight',
      'Clear history': 'Clear history',
      'Success, History cleared': 'Success, History cleared',
      'Settings': 'Settings',
      'Saved': 'Saved',
      'Scan result saved': 'Scan result saved',
      "Dark Mode": "Dark Mode",
      'Share': 'Share',
      'Delete': 'Delete',
      "Disease Library": "Disease Library",
      'Export Data': 'Export Data',
      'Search': 'Search',
      'Cancel': 'Cancel',
      'Export as CSV': 'Export as CSV',
      'Export as JSON': 'Export as JSON',


      //About the app
      'Setting': 'Settings',
      'About Smart Leaf Doctor': 'About Smart Leaf Doctor',
      'Smart Leaf Doctor is an offline mobile app that helps farmers and agronomists quickly identify crop diseases by analyzing leaf images. It provides instant, reliable results to help protect your crops and improve yields.': 'Smart Leaf Doctor is an offline mobile app that helps farmers and agronomists quickly identify crop diseases by analyzing leaf images. It provides instant, reliable results to help protect your crops and improve yields.',
      "About the App": "About the App",
      "App Overview": "App Overview",
      "AI Leaf Detector is an offline mobile app that helps farmers and agronomists quickly identify crop diseases by analyzing leaf images. It provides instant, reliable results to help protect your crops and improve yields.": "AI Leaf Detector is an offline mobile app that helps farmers and agronomists quickly identify crop diseases by analyzing leaf images. It provides instant, reliable results to help protect your crops and improve yields.",
      "Key Features": "Key Features",
      "Offline AI-based disease detection": "Offline AI-based disease detection",
      "Supports multiple crops (e.g., cassava, maize)": "Supports multiple crops (e.g., cassava, maize)",
      "Shows confidence scores for each prediction": "Shows confidence scores for each prediction",
      "Stores past scans for offline reference": "Stores past scans for offline reference",
      "Easy-to-use interface with multilingual support": "Easy-to-use interface with multilingual support",
      "Light/Dark mode toggle for accessibility": "Light/Dark mode toggle for accessibility",
      "Works without internet or mobile data": "Works without internet or mobile data",
      "Benefits": "Benefits",
      "Save time compared to manual inspection": "Save time compared to manual inspection",
      "Reduce crop loss through early detection": "Reduce crop loss through early detection",
      "Works anywhere, even in remote areas": "Works anywhere, even in remote areas",
      "Helps make informed farming decisions": "Helps make informed farming decisions",
      "Empowers farmers with instant, offline insights": "Empowers farmers with instant, offline insights",
      "Credits & Contact": "Credits & Contact",
      "Developed by: Mahamat Ali Abderaman": "Developed by: Mahamat Ali Abderaman",
      "For feedback or support:": "For feedback or support:",
      "Privacy & Data": "Privacy & Data",
      "This app stores scan history locally on your device. No personal data is shared or uploaded.": "This app stores scan history locally on your device. No personal data is shared or uploaded.",
      "Languages Supported": "Languages Supported",
      "English, Français, العربية, Kinyarwanda": "English, Français, العربية, Kinyarwanda",
      "Version Info": "Version Info",
      "Version: 1.0.0": "Version: 1.0.0",
      "Last updated: November 2025": "Last updated: November 2025",
      "Close": "Close",

      // New Keys
      'history': 'History',
      'no_history': 'No history yet',
      'Speak': 'Speak',
      'export_pdf': 'Export PDF',

      //  Best Practices Page
      'best_practices': 'Best Practices',
      'field_tips': 'Field Tips for Better Photos',
      'tip_photo': 'Take clear photos',
      'photo_tip1': 'Place one leaf in frame, fill most of the image.',
      'tip_light': 'Use good lighting',
      'photo_tip2': 'Prefer natural daylight. Avoid heavy shadows.',
      'tip_single_leaf': 'Capture a single leaf',
      'photo_tip3': 'Avoid multiple overlapping leaves in the image.',
      'tip_distance': 'Keep proper distance',
      'photo_tip4': 'Don\'t be too far or too close; keep leaf details visible.',
      'farm_management': 'Farm Management',
      'farm_management_text': 'Regular scouting, crop rotation, and using resistant varieties help prevent major outbreaks.',

      //  Popup & buttons
      'recommendation': 'Recommendation',
      'copy_advice': 'Copy Advice',
      'copied': 'Copied',
      'copied_message': 'Advice copied to clipboard',

      //  Disease Messages
      'cassava_mosaic': 'Cassava mosaic detected. Use clean planting cuttings, remove infected plants early, and control whiteflies to stop the virus.',
      'cassava_healthy_msg': 'Your cassava plant looks healthy. Keep using clean planting material, control weeds, and monitor regularly for early signs of disease.',
      'maize_blight_msg': 'Maize Leaf Blight detected. Rotate crops, avoid overhead irrigation, and apply fungicides if symptoms continue.',
      'maize_healthy_msg': 'Your maize plant is in good condition. Maintain proper spacing, rotate crops, and ensure balanced fertilization for strong growth.',
      'cassava_brown_streak_msg':'Cassava brown streak detected. Use resistant cassava varieties, remove infected plants promptly, and practice crop rotation to reduce spread.',
      'maize_gray_leaf_spot_msg':'Maize gray leaf spot detected. Apply recommended fungicides, rotate crops, and plant resistant maize hybrids to protect yield.',
      'unknown_crop_msg': 'Oops! That’s not a cassava or maize leaf. Please upload or capture a leaf from one of those crops to get accurate results.',

      // Symptoms & Treatment
      'cmd_symptoms': 'Yellowing, mosaic leaf patterns, and leaf distortion.',
      'cmd_treatment': 'Use CMD-resistant varieties, remove infected plants.',
      'cbsd_symptoms': 'Brown streaks on stems and roots, necrotic lesions on leaves, root rot, reduced starch content.',
      'cbsd_treatment': 'Plant resistant cassava varieties, remove and destroy infected plants, practice crop rotation, and use clean planting materials.',
      'cassava_healthy_symptoms': 'No visible symptoms.',
      'cassava_healthy_treatment': 'Maintain good farming practices.',
      'mlb_symptoms': 'Brown spindle-shaped lesions spreading along the veins.',
      'mlb_treatment': 'Use resistant hybrids and apply fungicides if necessary.',
      'mgls_symptoms': 'Gray rectangular lesions on maize leaves, reduced photosynthesis, premature leaf death, yield loss.',
      'mgls_treatment': 'Apply recommended fungicides, rotate crops, use resistant maize hybrids, and ensure proper field sanitation.',
      'maize_healthy_symptoms': 'No visible disease.',
      'maize_healthy_treatment': 'Keep monitoring plants.',
    },


    'fr': {
      // Status
      'status_healthy': 'Sain',
      'status_diseased': 'Malade',
      'status_unknown': 'Inconnu',

// Crops
      'crop_maize': 'Maïs',
      'crop_cassava': 'Manioc',
      'crop_unknown': 'Inconnu',

// Diagnoses
      'diagnosis_mosaic': 'Maladie de la mosaïque',
      'diagnosis_leaf_blight': 'Brûlure des feuilles',
      'diagnosis_gray_leaf_spot': 'Tache grise des feuilles',
      'diagnosis_brown_streak': 'Maladie des stries brunes',
      'diagnosis_healthy': 'Sain',
      'diagnosis_unknown': 'Inconnu',


      'analyzing_leaf': 'Analyse de la feuille...',

      'app_title': 'Docteur Feuille Intelligent',
      'scan_now': 'Scanner la feuille',
      'select_image': 'Sélectionner une image',
      'capture_image': 'Capturer une image',
      'analysis_result': 'Résultat d\'analyse',
      'crop_type': 'Type de culture',
      'diagnosis': 'Diagnostic',
      'confidence': 'Confiance',
      'symptoms': 'Symptômes',
      'treatment': 'Traitement',
      'healthy_leaf': 'Feuille saine ✅',
      'unknown_crop': 'Culture inconnue',
      'unknown_disease': 'Maladie inconnue',
      'try_again': 'Réessayer',
      'result': 'Résultat',
      'advice': 'Conseil',
      'success': 'Succès',
      'clear_photo': 'Veuillez télécharger une photo claire de la feuille.',
      'language': 'Langue',
      'ok': 'OK',
      'retake_photo': 'Reprendre la photo',
      'Scan & diagnose crop diseases instantly': 'Scannez et diagnostiquez les maladies des cultures instantanément',
      'Empowering agriculture through smart image diagnostics': "Rendre l'agriculture plus performante grâce au diagnostic d'images intelligent",
      'Oops! That’s not a cassava or maize leaf. Please upload or capture a leaf from one of those crops to get accurate results.': "Oups ! Ce n’est pas une feuille de manioc ou de maïs. Veuillez télécharger ou capturer une feuille de l’une de ces cultures pour obtenir des résultats précis",
      'Unknown': 'Inconnue',
      'Share': 'Partager',
      'Delete': 'Supprimer',
      "Disease Library": "Bibliothèque des maladies",
      'Export Data': 'Exporter les données',
      'Search': 'Rechercher',
      'Cancel': 'Annuler',
      'Export as CSV': 'Exporter au format CSV',
      'Export as JSON': 'Exporter au format JSON',

      'none': 'aucune',

      'cassava_brown_streak_msg': 'Présence de striures brunes sur le manioc. Utilisez des variétés de manioc résistantes, éliminez rapidement les plants infectés et pratiquez la rotation des cultures pour limiter la propagation.',
      'maize_gray_leaf_spot_msg': 'Présence de taches grises sur le maïs. Appliquer les fongicides recommandés, pratiquer la rotation des cultures et planter des hybrides de maïs résistants pour protéger les rendements.',
      'unknown_crop_msg': "Oups ! Ce n’est pas une feuille de manioc ou de maïs. Veuillez télécharger ou capturer une feuille de l’une de ces cultures pour obtenir des résultats précis",
      'cassava': 'manioc',
      'maize': 'maïs',
      'Cassava_Healthy': 'Manioc_Sain',
      'Cassava_Mosaic_Disease': 'Maladie de la mosaïque du manioc',
      'Maize_Healthy': 'Maïs_Sain',
      'Maize_Leaf_Blight': 'Mildiou des feuilles de maïs',
      'Cassava_Brown_Streak_Disease':'Maladie des stries brunes du manioc',
      'Maize_Gray_Leaf_Spot':'Taches grises des feuilles du maïs',
      'Clear history': "Effacer l'historiques",
      'Success, History cleared': "Succès, l'histoire est effacée",
      'Settings': 'Paramètres',
      'Saved': 'Enregistré',
      'Scan result saved': "Résultat de l'analyse enregistré",
      "Dark Mode": 'Mode Sombre',

      // About the app
      'Setting': 'Paramètres',
      'About Smart Leaf Doctor': 'À propos de Smart Leaf Doctor',
      'Smart Leaf Doctor is an offline mobile app that helps farmers and agronomists quickly identify crop diseases by analyzing leaf images. It provides instant, reliable results to help protect your crops and improve yields.': 'Smart Leaf Doctor est une application mobile hors ligne qui aide les agriculteurs et les agronomes à identifier rapidement les maladies des cultures en analysant les images des feuilles. Elle fournit des résultats instantanés et fiables pour protéger vos cultures et améliorer les rendements.',
      "About the App": "À propos de l'application",
      "App Overview": "Présentation de l'application",
      "AI Leaf Detector is an offline mobile app that helps farmers and agronomists quickly identify crop diseases by analyzing leaf images. It provides instant, reliable results to help protect your crops and improve yields.": "AI Leaf Detector est une application mobile hors ligne qui aide les agriculteurs et les agronomes à identifier rapidement les maladies des cultures en analysant des images de feuilles. Elle fournit des résultats instantanés et fiables pour protéger vos cultures et améliorer les rendements.",
      "Key Features": "Fonctionnalités clés",
      "Offline AI-based disease detection": "Détection des maladies basée sur l'IA hors ligne",
      "Supports multiple crops (e.g., cassava, maize)": "Prend en charge plusieurs cultures (ex. : manioc, maïs,)",
      "Shows confidence scores for each prediction": "Affiche les scores de confiance pour chaque prédiction",
      "Stores past scans for offline reference": "Stocke les analyses précédentes pour consultation hors ligne",
      "Easy-to-use interface with multilingual support": "Interface facile à utiliser avec prise en charge multilingue",
      "Light/Dark mode toggle for accessibility": "Commutateur mode clair/sombre pour l'accessibilité",
      "Works without internet or mobile data": "Fonctionne sans internet ni données mobiles",
      "Benefits": "Avantages",
      "Save time compared to manual inspection": "Gagnez du temps par rapport à l'inspection manuelle",
      "Reduce crop loss through early detection": "Réduisez les pertes de récolte grâce à une détection précoce",
      "Works anywhere, even in remote areas": "Fonctionne partout, même dans les zones reculées",
      "Helps make informed farming decisions": "Aide à prendre des décisions agricoles éclairées",
      "Empowers farmers with instant, offline insights": "Donne aux agriculteurs des informations instantanées et hors ligne",
      "Credits & Contact": "Crédits et contact",
      "Developed by: Mahamat Ali Abderaman": "Développé par : Mahamat Ali Abderaman",
      "For feedback or support:": "Pour des commentaires ou de l'assistance :",
      "Privacy & Data": "Confidentialité et données",
      "This app stores scan history locally on your device. No personal data is shared or uploaded.": "Cette application stocke l'historique des analyses localement sur votre appareil. Aucune donnée personnelle n'est partagée ou téléchargée.",
      "Languages Supported": "Langues prises en charge",
      "English, Français, العربية, Kinyarwanda": "Anglais, Français, Arabe, Kinyarwanda",
      "Version Info": "Informations sur la version",
      "Version: 1.0.0": "Version : 1.0.0",
      "Last updated: November 2025": "Dernière mise à jour : Novembre 2025",
      "Close": "Fermer",

      //  New Keys
      'history': 'Historique',
      'no_history': 'Aucun historique pour le moment',
      'Speak': 'Parler',
      'export_pdf': 'Exporter en PDF',

      //  Best Practices
      'best_practices': 'Bonnes pratiques',
      'field_tips': 'Conseils pour de meilleures photos',
      'tip_photo': 'Prenez des photos claires',
      'photo_tip1': 'Placer une seule feuille dans le cadre, remplissez l’image.',
      'tip_light': 'Utilisez une bonne lumière',
      'photo_tip2': 'Lumière naturelle idéale. Évitez les ombres.',
      'tip_single_leaf': 'Capturez une seule feuille',
      'photo_tip3': 'Évitez plusieurs feuilles superposées.',
      'tip_distance': 'Gardez la bonne distance',
      'photo_tip4': 'Pas trop loin, pas trop près. Gardez les détails visibles.',
      'farm_management': 'Gestion agricole',
      'farm_management_text': 'Inspection régulière, rotation des cultures et variétés résistantes.',

      'recommendation': 'Recommandation',
      'copy_advice': 'Copier le conseil',
      'copied': 'Copié',
      'copied_message': 'Conseil copié',

      'cassava_mosaic': 'Mosaïque du manioc détectée. Utilisez des boutures saines, éliminez les plantes infectées tôt et contrôlez les mouches blanches.',
      'cassava_healthy_msg': 'Votre manioc est en bonne santé. Utilisez des boutures propres, désherbez régulièrement et surveillez les signes de maladie.',
      'maize_blight_msg': 'Brûlure des feuilles du maïs détectée. Faites la rotation des cultures, évitez l’irrigation par aspersion et utilisez des fongicides si nécessaire.',
      'maize_healthy_msg': 'Votre maïs est en bon état. Respectez les espacements, faites la rotation des cultures et fertilisez correctement.',

      'cmd_symptoms': 'Jaunissement et motifs en mosaïque.',
      'cmd_treatment': 'Utiliser des variétés résistantes, éliminer les plantes infectées.',
      'cbsd_symptoms': 'Stries brunes sur les tiges et les racines, lésions nécrotiques sur les feuilles, pourriture des racines, teneur réduite en amidon.',
      'cbsd_treatment':'Plantez des variétés de manioc résistantes, éliminez et détruisez les plants infectés, pratiquez la rotation des cultures et utilisez du matériel de plantation sain.',
      'cassava_healthy_symptoms': 'Aucun symptôme visible.',
      'cassava_healthy_treatment': 'Maintenir de bonnes pratiques agricoles.',
      'mlb_symptoms': 'Lésions brunâtres le long des nervures.',
      'mlb_treatment': 'Variétés résistantes, fongicides si nécessaire.',
      'mgls_symptoms': 'Lésions rectangulaires grises sur les feuilles de maïs, photosynthèse réduite, dépérissement prématuré des feuilles, perte de rendement.',
      'mgls_treatment': 'Appliquer les fongicides recommandés, pratiquer la rotation des cultures, utiliser des hybrides de maïs résistants et assurer une bonne hygiène des parcelles.',
      'maize_healthy_symptoms': 'Aucun signe de maladie.',
      'maize_healthy_treatment': 'Continuer à surveiller la culture.',
    },


    'ar': {
      // Status
      'status_healthy': 'سليم',
      'status_diseased': 'مصاب',
      'status_unknown': 'غير معروف',

// Crops
      'crop_maize': 'الذرة',
      'crop_cassava': 'الكسافا',
      'crop_unknown': 'غير معروف',

// Diagnoses
      'diagnosis_mosaic': 'مرض الفسيفساء',
      'diagnosis_leaf_blight': 'لفحة الأوراق',
      'diagnosis_gray_leaf_spot': 'بقعة الأوراق الرمادية',
      'diagnosis_brown_streak': 'مرض الخطوط البنية',
      'diagnosis_healthy': 'سليم',
      'diagnosis_unknown': 'غير معروف',


      'analyzing_leaf': 'جارٍ تحليل الورقة...',

      'app_title': 'طبيب الأوراق الذكي',
      'scan_now': 'فحص الورقة',
      'select_image': 'اختيار صورة',
      'capture_image': 'التقاط صورة',
      'analysis_result': 'نتيجة التحليل',
      'crop_type': 'نوع المحصول',
      'diagnosis': 'التشخيص',
      'confidence': 'نسبة الثقة',
      'symptoms': 'الأعراض',
      'treatment': 'العلاج',
      'healthy_leaf': 'ورقة سليمة ✅',
      'unknown_crop': 'محصول غير معروف',
      'unknown_disease': 'مرض غير معروف',
      'try_again': 'حاول مرة أخرى',
      'result': 'النتيجة',
      'advice': 'نصيحة',
      'success': 'نجاح',
      'clear_photo': 'يرجى رفع صورة واضحة للورقة.',
      'language': 'اللغة',
      'ok': 'حسناً',
      'retake_photo': 'إعادة التصوير',
      'Scan & diagnose crop diseases instantly': 'مسح وتشخيص أمراض المحاصيل على فورًا',
      'Empowering agriculture through smart image diagnostics': 'تمكين الزراعة من خلال تشخيصات الصور الذكية',
      'Oops! That’s not a cassava or maize leaf. Please upload or capture a leaf from one of those crops to get accurate results.':'عفوًا! هذه ليست ورقة من نبات الكسافا أو الذرة. يُرجى تحميل أو التقاط صورة من أحد هذين المحصولين للحصول على نتائج دقيقة.',
      'Unknown': 'مجهول',
      'Share': 'يشارك',
      'Delete': 'يمسح',
      "Disease Library": "مكتبة الأمراض",
      'Export Data': 'تصدير البيانات',
      'Search': 'بحث',
      'Cancel': 'إلغاء',
      'Export as CSV': 'تصدير بصيغة CSV',
      'Export as JSON': 'تصدير بصيغة JSON',

      'none': 'لا أحد',
      'cassava_brown_streak_msg': ' تم اكتشاف خطوط بنية على نبات الكسافا. استخدم أصنافًا مقاومة، وأزل النباتات المصابة فورًا، ومارس تناوبًا زراعيًا للحد من انتشار المرض.',
      'maize_gray_leaf_spot_msg': 'تم اكتشاف بقعة رمادية على أوراق الذرة. استخدم مبيدات الفطريات الموصى بها، ودرّب المحاصيل، وازرع أصنافًا هجينة مقاومة للذرة لحماية المحصول.',
      'unknown_crop_msg': 'عفوًا! هذه ليست ورقة من نبات الكسافا أو الذرة. يُرجى تحميل أو التقاط صورة من أحد هذين المحصولين للحصول على نتائج دقيقة.',
      'cassava': 'الكسافا',
      'maize': 'الذرة',
      'Cassava_Healthy': 'الكسافا_الصحي',
      'Cassava_Mosaic_Disease': 'مرض فسيفساء الكسافا',
      'Maize_Healthy': 'ذرة صحية',
      'Maize_Leaf_Blight': 'مرض أوراق الذرة',
      'Cassava_Brown_Streak_Disease':'داء الخطوط البنية في الكسافا',
      'Maize_Gray_Leaf_Spot':'بقع أوراق الذرة الرمادية',
      'Clear history': 'مسح التاريخ',
      'Success, History cleared': 'النجاح، تم مسح التاريخ',
      'Settings': 'إعدادات',
      'Saved': 'تم الحفظ.',
      'Scan result saved': 'تم حفظ نتيجة المسح',
      'Dark Mode':'الوضع المظلم',

      // About the app
      'Setting': 'الإعدادات',
      'About Smart Leaf Doctor': 'حول تطبيق Smart Leaf Doctor',
      'Smart Leaf Doctor is an offline mobile app that helps farmers and agronomists quickly identify crop diseases by analyzing leaf images. It provides instant, reliable results to help protect your crops and improve yields.': 'Smart Leaf Doctor هو تطبيق يعمل دون اتصال يساعد المزارعين والمهندسين الزراعيين على تحديد أمراض المحاصيل بسرعة من خلال تحليل صور الأوراق. يوفر نتائج فورية وموثوقة لحماية محاصيلك وتحسين الإنتاجية.',
      "About the App": "حول التطبيق",
      "App Overview": "نظرة عامة على التطبيق",
      "AI Leaf Detector is an offline mobile app that helps farmers and agronomists quickly identify crop diseases by analyzing leaf images. It provides instant, reliable results to help protect your crops and improve yields.": "كاشف أوراق الذكاء الاصطناعي هو تطبيق جوال يعمل دون اتصال يساعد المزارعين والمهندسين الزراعيين على تحديد أمراض المحاصيل بسرعة من خلال تحليل صور الأوراق. يوفر نتائج فورية وموثوقة لحماية المحاصيل وتحسين الإنتاجية.",
      "Key Features": "الميزات الرئيسية",
      "Offline AI-based disease detection": "اكتشاف الأمراض باستخدام الذكاء الاصطناعي دون اتصال",
      "Supports multiple crops (e.g., cassava, maize)": "يدعم محاصيل متعددة (مثل الكسافا، الذرة)",
      "Shows confidence scores for each prediction": "يعرض درجات الثقة لكل تنبؤ",
      "Stores past scans for offline reference": "يخزن الفحوصات السابقة للرجوع إليها دون اتصال",
      "Easy-to-use interface with multilingual support": "واجهة سهلة الاستخدام مع دعم متعدد اللغات",
      "Light/Dark mode toggle for accessibility": "تبديل الوضع الفاتح/الداكن لتحسين الوصول",
      "Works without internet or mobile data": "يعمل بدون إنترنت أو بيانات الهاتف",
      "Benefits": "الفوائد",
      "Save time compared to manual inspection": "يوفر الوقت مقارنة بالفحص اليدوي",
      "Reduce crop loss through early detection": "يقلل من خسائر المحاصيل من خلال الكشف المبكر",
      "Works anywhere, even in remote areas": "يعمل في أي مكان، حتى في المناطق النائية",
      "Helps make informed farming decisions": "يساعد في اتخاذ قرارات زراعية مدروسة",
      "Empowers farmers with instant, offline insights": "يمكّن المزارعين من الحصول على معلومات فورية دون اتصال",
      "Credits & Contact": "الاعتمادات والتواصل",
      "Developed by: Mahamat Ali Abderaman": "تم تطويره بواسطة: محمد علي عبد الرحمن",
      "For feedback or support:": "للتعليقات أو الدعم:",
      "Privacy & Data": "الخصوصية والبيانات",
      "This app stores scan history locally on your device. No personal data is shared or uploaded.": "يتم تخزين سجل الفحص محليًا على جهازك. لا يتم مشاركة أو تحميل أي بيانات شخصية.",
      "Languages Supported": "اللغات المدعومة",
      "English, Français, العربية, Kinyarwanda": "الإنجليزية، الفرنسية، العربية، الكينيارواندية",
      "Version Info": "معلومات الإصدار",
      "Version: 1.0.0": "الإصدار: 1.0.0",
      "Last updated: November 2025": "آخر تحديث: نوفمبر 2025",
      "Close": "إغلاق",

      //  New Keys
      'history': 'السجل',
      'no_history': 'لا يوجد سجل بعد',
      'Speak': 'تحدث',
      'export_pdf': 'تصدير PDF',

      'best_practices': 'أفضل الممارسات',
      'field_tips': 'نصائح للحصول على صور أفضل',
      'tip_photo': 'التقط صورًا واضحة',
      'photo_tip1': 'ضع ورقة واحدة في الإطار واملأ معظم الصورة.',
      'tip_light': 'استخدم إضاءة جيدة',
      'photo_tip2': 'إضاءة النهار أفضل، تجنب الظلال القوية.',
      'tip_single_leaf': 'التقط ورقة واحدة فقط',
      'photo_tip3': 'تجنب الأوراق المتداخلة.',
      'tip_distance': 'حافظ على مسافة مناسبة',
      'photo_tip4': 'لا تكن قريبًا أو بعيدًا جدًا.',
      'farm_management': 'إدارة المزرعة',
      'farm_management_text': 'الفحص الدوري وتدوير المحاصيل واستخدام أصناف مقاومة يقلل من الأمراض.',

      'recommendation': 'توصية',
      'copy_advice': 'نسخ النصيحة',
      'copied': 'تم النسخ',
      'copied_message': 'تم نسخ النصيحة',

      'cassava_mosaic': 'تم اكتشاف مرض الموزاييك في الكسافا. استخدم قصاصات نظيفة للزراعة، وقم بإزالة النباتات المصابة في وقت مبكر، وقم بالسيطرة على الذباب الأبيض لإيقاف الفيروس.',
      'cassava_healthy_msg': 'يبدو نبات الكسافا الخاص بك سليمًا. استمر في استخدام مواد زراعة نظيفة، وكافح الأعشاب الضارة، وراقبه بانتظام لاكتشاف العلامات المبكرة للمرض.',
      'maize_blight_msg': 'تم اكتشاف لفحة أوراق الذرة. قم بتدوير المحاصيل، وتجنب الري العلوي، واستخدم مبيدات الفطريات إذا استمرت الأعراض.',
      'maize_healthy_msg': 'نبتة الذرة لديك في حالة جيدة. حافظ على التباعد المناسب، ودرّب المحاصيل، وتأكد من التسميد المتوازن لنمو قوي.',

      'cmd_symptoms': 'اصفرار وتشوه الأوراق.',
      'cmd_treatment': 'استخدم أصناف مقاومة وأزل النباتات المصابة.',
      'cbsd_symptoms': 'خطوط بنية على السيقان والجذور، آفات نخرية على الأوراق، تعفن الجذور، انخفاض محتوى النشا.',
      'cbsd_treatment': 'ازرع أصناف الكسافا المقاومة، وأزل النباتات المصابة وأتلفها، ومارس تناوب المحاصيل، واستخدم مواد زراعة نظيفة.',
      'cassava_healthy_symptoms': 'لا توجد أعراض.',
      'cassava_healthy_treatment': 'استمر بالممارسات الجيدة.',
      'mlb_symptoms': 'بقع بنية على الأوراق.',
      'mlb_treatment': 'استخدم أصناف مقاومة ورش مبيد عند الحاجة.',
      'mgls_symptoms': 'آفات رمادية مستطيلة الشكل على أوراق الذرة، انخفاض التمثيل الضوئي، موت مبكر للأوراق، نقص في المحصول.',
      'mgls_treatment': 'استخدام مبيدات الفطريات الموصى بها، تدوير المحاصيل، استخدام هجن ذرة مقاومة، والتأكد من نظافة الحقل بشكل صحيح.',
      'maize_healthy_symptoms': 'لا توجد أعراض.',
      'maize_healthy_treatment': 'استمر في المراقبة.',
    },


    'rw': {
      // Status
      'status_healthy': 'Nta ndwara',
      'status_diseased': 'Ifite indwara',
      'status_unknown': 'Ntibizwi',

// Crops
      'crop_maize': 'Ibigori',
      'crop_cassava': 'Imyumbati',
      'crop_unknown': 'Ntibizwi',

// Diagnoses
      'diagnosis_mosaic': 'Indwara ya mozayike',
      'diagnosis_leaf_blight': 'Indwara y\'icuraburindi',
      'diagnosis_gray_leaf_spot': 'Indwara y’icyitambambuga',
      'diagnosis_brown_streak': 'Indwara y’umurongo w’umukara',
      'diagnosis_healthy': 'Nta ndwara',
      'diagnosis_unknown': 'Ntibizwi',


      'analyzing_leaf': 'Iri gusesengura ibibabi...',

      'app_title': 'Umuganga w\'Amababi',
      'scan_now': 'Sikana Ishyamba',
      'select_image': 'Hitamo Ifoto',
      'capture_image': 'Fata Ifoto',
      'analysis_result': 'Ibisubizo',
      'crop_type': 'Ubwoko bw\'Igihingwa',
      'diagnosis': 'Ibisubizo',
      'confidence': 'Ubwize',
      'symptoms': 'Ibimenyetso',
      'treatment': 'Uburyo bwo Kuvura',
      'healthy_leaf': 'Ikibabi Ni Cyiza ✅',
      'unknown_crop': 'Igihingwa Kitaramenyekana',
      'unknown_disease': 'Indwara Itazwi',
      'try_again': 'Ongera Ugerageze',
      'result': 'Ibisubizo',
      'advice': 'Inama',
      'success': 'Byagenze Neza',
      'clear_photo': 'Shyiraho ifoto isobanutse.',
      'language': 'Ururimi',
      'ok': 'OK',
      'retake_photo': 'Subiramo Ifoto',
      'Scan & diagnose crop diseases instantly': 'Sikana kandi usuzume indwara zibihingwa ako kanya',
      'Empowering agriculture through smart image diagnostics': 'Guha imbaraga ubuhinzi binyuze mu gusuzuma amashusho meza',
      'Oops! That’s not a cassava or maize leaf. Please upload or capture a leaf from one of those crops to get accurate results.': 'Oops! Ntabwo ari ikibabi cyangwa ikibabi cyibigori. Nyamuneka ohereza cyangwa ufate ikibabi muri kimwe muri ibyo bihingwa kugirango ubone ibisubizo nyabyo.',
      'Unknown': 'Ntazwi',
      'Share': 'Gusangiza',
      'Delete': 'supprimer',
      "Disease Library": "Isomero ry'indwara",
      'Export Data': 'Kohereza amakuru yo mu mahanga',
      'Search': 'Shakisha',
      'Cancel': 'Hagarika',
      'Export as CSV': 'Kohereza muri CSV',
      'Export as JSON': 'Kohereza muri JSON',

      'none': 'nta',
      'cassava_brown_streak_msg': "Imirongo y'umukara w'imyumbati yabonetse. Koresha ubwoko bw'imyumbati irwanya indwara, kura ibimera byanduye vuba, kandi uhindure ibihingwa kugira ngo ugabanye ikwirakwira ry'ibimera.",
      'maize_gray_leaf_spot_msg': "Ibara ry'ikibabi cy'umukara cy'ibigori ryaragaragaye. Shyira imiti yica udukoko ikoreshwa mu guhinga, uzungurure imyaka, kandi uhinge ibigori byihanganira ibimera kugira ngo birinde umusaruro.",
      'unknown_crop_msg': 'Oops! Ntabwo ari ikibabi cyangwa ikibabi cyibigori. Nyamuneka ohereza cyangwa ufate ikibabi muri kimwe muri ibyo bihingwa kugirango ubone ibisubizo nyabyo.',
      'cassava': 'imyumbati',
      'maize': 'ibigori',
      'Cassava_Healthy': 'Imyumbati_Ubuzima',
      'Cassava_Mosaic_Disease': 'Imyumbati_Mosaic_Disease',
      'Maize_Healthy': 'Ibigori_Ubuzima bwiza',
      'Maize_Leaf_Blight': 'Ibigori_Ibabi_Umucyo',
      'Cassava_Brown_Streak_Disease':'Indwara_y_Umuhondo_w_Imyuka_Ya_Cassava',
      'Maize_Gray_Leaf_Spot':'Ibice_by_Ibara_ry_Imvi_y_Ibabi_ry',
      'Clear history': 'Sobanura amateka',
      'Success, History cleared': 'Intsinzi, Amateka yarahanaguwe',
      'Settings': 'Igenamiterere',
      'Saved': 'Yakijijwe',
      'Scan result saved': 'Gusikana ibisubizo byakijijwe',
      'Dark Mode': 'Uburyo bwijimye',

      // About the app
      'Setting': 'Ibyihariye',
      'About Smart Leaf Doctor': 'Ibyerekeye Smart Leaf Doctor',
      'Smart Leaf Doctor is an offline mobile app that helps farmers and agronomists quickly identify crop diseases by analyzing leaf images. It provides instant, reliable results to help protect your crops and improve yields.': 'Smart Leaf Doctor ni porogaramu ya telefone ikora idafite internet ifasha abahinzi n’abashakashatsi kumenya indwara z’ibihingwa vuba binyuze mu gusuzuma amashusho y’amababi. Itanga ibisubizo byihuse kandi byizewe kugira ngo urinde imyaka yawe kandi wongere umusaruro.',
      "About the App": "Ibyerekeye Porogaramu",
      "App Overview": "Incamake ya Porogaramu",
      "AI Leaf Detector is an offline mobile app that helps farmers and agronomists quickly identify crop diseases by analyzing leaf images. It provides instant, reliable results to help protect your crops and improve yields.": "AI Leaf Detector ni porogaramu ya telefoni ikora nta internet, ifasha abahinzi n’abajyanama b’ubuhinzi kumenya indwara z’ibihingwa binyuze mu gusuzuma amashusho y’amababi. Itanga ibisubizo byihuse kandi byizewe mu kurinda imyaka no kongera umusaruro.",
      "Key Features": "Ibikubiye muri Porogaramu",
      "Offline AI-based disease detection": "Kumenya indwara hifashishijwe AI nta internet",
      "Supports multiple crops (e.g., cassava, maize)": "Ishyigikira ibihingwa bitandukanye (nka manioka, ibigori)",
      "Shows confidence scores for each prediction": "Yerekana amanota y’icyizere kuri buri gisubizo",
      "Stores past scans for offline reference": "Ibitangazwa byabitswe bishobora kurebwa nta internet",
      "Easy-to-use interface with multilingual support": "Ifite imikorere yoroshye kandi ishyigikira indimi zitandukanye",
      "Light/Dark mode toggle for accessibility": "Guhindura hagati y’urumuri n’umwijima ku bworoherezwa",
      "Works without internet or mobile data": "Ikora nta internet cyangwa data ya telefoni",
      "Benefits": "Ibyiza",
      "Save time compared to manual inspection": "Izigama igihe ugereranyije no gusuzuma intoki",
      "Reduce crop loss through early detection": "Igabanya igihombo cy’imyaka binyuze mu kumenya indwara hakiri kare",
      "Works anywhere, even in remote areas": "Ikora ahantu hose, n’ahitaruye",
      "Helps make informed farming decisions": "Ifasha gufata ibyemezo by’ubuhinzi bishingiye ku makuru",
      "Empowers farmers with instant, offline insights": "Iha abahinzi ubushobozi bwo kubona amakuru yihuse nta internet",
      "Credits & Contact": "Abayikoze & Aho wabahamagara",
      "Developed by: Mahamat Ali Abderaman": "Yakozwe na: Mahamat Ali Abderaman",
      "For feedback or support:": "Kubijyanye n’ibitekerezo cyangwa ubufasha:",
      "Privacy & Data": "Ubuzima bwite & Amakuru",
      "This app stores scan history locally on your device. No personal data is shared or uploaded.": "Iyi porogaramu ibika amateka y’isuzuma kuri telefoni yawe. Nta makuru yihariye asangirwa cyangwa ashyirwa kuri internet.",
      "Languages Supported": "Indimi zishyigikiwe",
      "English, Français, العربية, Kinyarwanda": "Icyongereza, Igifaransa, Icyarabu, Ikinyarwanda",
      "Version Info": "Amakuru ku Isura",
      "Version: 1.0.0": "Verisiyo: 1.0.0",
      "Last updated: November 2025": "Yavuguruwe: Ugushyingo 2025",
      "Close": "Funga",


      //  New Keys
      'history': 'Amateka',
      'no_history': 'Nta mateka araboneka',
      'Speak': 'Vuga',
      'export_pdf': 'Ohereza muri PDF',

      'best_practices': 'Inama Nziza',
      'field_tips': 'Uko wafata ifoto nziza',
      'tip_photo': 'Fata ifoto isobanutse',
      'photo_tip1': 'Shyira ikibabi kimwe mu ifoto, gikinge neza.',
      'tip_light': 'Koresha urumuri rwiza',
      'photo_tip2': 'Urumuri rw\'imunsi ni rwo rwiza, irinda igicucu.',
      'tip_single_leaf': 'Fata ikibabi kimwe',
      'photo_tip3': 'Irinde ibibabi byinshi mu ifoto.',
      'tip_distance': 'Fata ahantu hakwiye',
      'photo_tip4': 'Ntube kure cyane cyangwa hafi cyane.',
      'farm_management': 'Imicungire y\'umurima',
      'farm_management_text': 'Gusura umurima kenshi no guhinduranya imyaka birinda indwara.',

      'recommendation': 'Inama',
      'copy_advice': 'Kopera Inama',
      'copied': 'Yakopiwe',
      'copied_message': 'Inama yakopiwe',

      'cassava_mosaic': 'Indwara ya mosaic ya manioke yabonetse. - Koresha ibihingwa byiza, kuraho ibimera bifashwe hakiri kare, kandi ugenzure udusimba tw’umweru.',
      'cassava_healthy_msg': 'Igihingwa cya kasava kirakomeye. Koresha ibihingwa byiza, kuraho ibyatsi bibi, kandi ukurikirane ibimenyetso by’indwara.',
      'maize_blight_msg': 'Indwara ya blight ku masaka yabonetse. - Hindura imyaka, wirinde kuvomera uvuye hejuru, kandi ukoreshe imiti yica udukoko niba ibimenyetso bikomeje.',
      'maize_healthy_msg': '- Igihembwe cya ibigori kirameze neza. Kubahiriza intera, guhinduranya imyaka, no gukoresha ifumbire iboneye birafasha.',

      'cmd_symptoms': 'Ibibabi bihinduka kandi bigacikagurika.',
      'cmd_treatment': 'Koresha imbuto zirwanya indwara, ukuraho ibihingwa byanduye.',
      'cbsd_symptoms':"Imirongo y'umukara ku mizi no ku biti, udusebe twangiritse ku mababi, kubora kw'imizi, kugabanuka kw'ifu y'ifu.",
      'cbsd_treatment': "Tera ubwoko bw'imyumbati irwanya indwara, kurandura no kwangiza ibimera byanduye, shyira mu bikorwa gahunda yo guhinduranya ibihingwa, kandi ukoreshe ibikoresho byo gutera bisukuye.",
      'cassava_healthy_symptoms': 'Nta bimenyetso.',
      'cassava_healthy_treatment': 'Komeza usukure umurima neza.',
      'mlb_symptoms': 'Ibibara by\'umukara ku bibabi.',
      'mlb_treatment': 'Koresha imbuto nziza no gukoresha imiti mu gihe bikenewe.',
      'mgls_symptoms': "Ibisebe by'urukiramende ku mababi y'ibigori, kugabanuka kwa photosynthesis, gupfa kw'amababi imburagihe, gutakaza umusaruro.",
      'mgls_treatment': "mgls_treatment': 'Shyira imiti yica udukoko isabwa, hinduranya imyaka, koresha ubwoko bw'ibigori bwihanganira indwara, kandi urebe neza ko isuku ikwiye mu murima.",
      'maize_healthy_symptoms': 'Nta bimenyetso.',
      'maize_healthy_treatment': 'Komeza kugenzura.',
    },
  };
}
